from PyQt5 import QtWidgets
from datetime import datetime

class ChangeCompanyDialog(QtWidgets.QDialog):

    def __init__(self, name, country, yearOfEstablishment, *args, **kwargs):
        super(ChangeCompanyDialog, self).__init__(*args, **kwargs)
        self.setFixedHeight(225)
        self.setFixedWidth(400)
        self.setWindowTitle('Измменение киностудии')
        self.label = QtWidgets.QLabel('Наименование')
        self.label1 = QtWidgets.QLabel('Страна')
        self.label2 = QtWidgets.QLabel('Год основания')
        self.vBoxLayout = QtWidgets.QVBoxLayout()
        self.vBoxLayout.addWidget(self.label)
        self.vBoxLayout.addWidget(self.label1)
        self.vBoxLayout.addWidget(self.label2)
        self.widgetWithLabes = QtWidgets.QWidget()
        self.widgetWithLabes.setLayout(self.vBoxLayout)
        self.lineEdit = QtWidgets.QLineEdit(name)
        self.lineEdit1 = QtWidgets.QLineEdit(country)
        self.yearOfEstablishment = QtWidgets.QSpinBox()
        self.yearOfEstablishment.setMinimum(1900)
        self.yearOfEstablishment.setMaximum(datetime.now().year)
        self.yearOfEstablishment.setValue(yearOfEstablishment)
        self.vBoxLayout1 = QtWidgets.QVBoxLayout()
        self.vBoxLayout1.addWidget(self.lineEdit)
        self.vBoxLayout1.addWidget(self.lineEdit1)
        self.vBoxLayout1.addWidget(self.yearOfEstablishment)
        self.widgetWithData = QtWidgets.QWidget()
        self.widgetWithData.setLayout(self.vBoxLayout1)
        self.hBoxLayout = QtWidgets.QHBoxLayout()
        self.hBoxLayout.addWidget(self.widgetWithLabes)
        self.hBoxLayout.addWidget(self.widgetWithData)
        self.widgetWithTypesOfHall = QtWidgets.QWidget()
        self.widgetWithTypesOfHall.setLayout(self.hBoxLayout)
        self.addButton = QtWidgets.QPushButton('Изменить')
        self.addButton.clicked.connect(self.addButtonClicked)
        self.cancelButton = QtWidgets.QPushButton('Отменить')
        self.cancelButton.clicked.connect(self.close)
        self.hBoxLayout1 = QtWidgets.QHBoxLayout()
        self.hBoxLayout1.addWidget(self.addButton)
        self.hBoxLayout1.addWidget(self.cancelButton)
        self.widgetWithButtons = QtWidgets.QWidget()
        self.widgetWithButtons.setLayout(self.hBoxLayout1)
        self.vBoxLayout2 = QtWidgets.QVBoxLayout()
        self.vBoxLayout2.addWidget(self.widgetWithTypesOfHall)
        self.vBoxLayout2.addWidget(self.widgetWithButtons)
        self.setLayout(self.vBoxLayout2)

    def addButtonClicked(self):
        self.lineEdit.setEnabled(False)
        self.close()